### ISSUE TITLE
ZosDsn.createDsn returns Optional error when dataset exists

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#150]
Run new ZosDsn(connection).createDsn(testDataset, CreateParams.partioned()) with a dataset that already exists.

The output contains an unexpected error:

12:19:50.631 [main] DEBUG zosfiles.ZosDsn - https://ca31:1443/zosmf/restfiles/ds/NATCO02.TESTDATA
12:19:50.639 [main] DEBUG zosfiles.ZosDsn - {"secondary":1,"dsorg":"PO","recfm":"FB","dirblk":5,"blksize":6160,"alcunit":"CYL","primary":1,"lrecl":80}
12:19:51.725 [main] DEBUG rest.JsonPostRequest - JsonPostRequest::httpPost - Response statusCode 500, Response HttpResponseProxy{HTTP/1.1 500 Internal Server Error [X-Powered-By: Servlet/3.1, X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, Strict-Transport-Security: max-age=31536000; includeSubDomains, Content-Type: application/json; charset=UTF-8, Content-Length: 74, X-IBM-Txid: tx000000000005F4B1, Content-Language: en-US, Set-Cookie: jwtToken=eyJraWQiOiJvekdfeVNNSFJzVlFGbU4xbVZCZVMtV3RDdXBZMXItSzdld2JlbjA5SUJnIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJ0b2tlbl90eXBlIjoiQmVhcmVyIiwic3ViIjoibmF0Y28wMiIsInVwbiI6Im5hdGNvMDIiLCJncm91cHMiOlsiRlJBTUVXS0ciLCJDSE9SR1JQMiIsIkNIT1JHUlAzIiwiSVpVVU5HUlAiLCJJWlVTRUNBRCIsIkRBQVNHUlAiXSwicmVhbG0iOiJTQUZSZWFsbSIsImlzcyI6InpPU01GIiwiZXhwIjoxNjMxMzA2MTAyLCJpYXQiOjE2MzEyNzY3MDJ9.bYfeglRgOAhDC9VGaoYJOD90ii_1x2AHEEwHFvDKsZHxPfeltRsSrgbw7-7gHyNJby0f9xHC4j1h1RkDK4kZRhDHALYOAB1fvHKVmddKdacW0dw1M8nCUg2M6bnvMW2criJazqN1UD5OcgWsgUmfnq2Lyn5QET49LcC03tizCH4l8AM7Xka59vEMUPAVVTDIngGYpd-WywbQJ5QjeKAGt2Rjw2TLNbTr26CL4D4cDYXnjUtfiL7FwFrOX4DPpITiZdI7fxjhf302a6Cr9Kh1WluC3pBAsJnVjbEaIoC62lw_l6xobNcscZ8BctXut85DT03l3uuOo1eyiLsr6R0WqQ; Path=/; Secure; HttpOnly, Set-Cookie: LtpaToken2=2x+558vpLaSzmRX/VObK8v0DiDGN3X09NENbVxasR+RtSDl4Aog+U5cyFVUSe5Rz9Fb5Go/PEKOCA8pVavKV2JINMPCnfyspF4MwEqRcwFgH9nHh/Jq7oRM/oD6hDjWFpXa1Mn8Bx+ViAg6t1y+JCj27euIUhNuAA3to9S532GjYMkDk4/1xF159nNidpN53jFr20hhmahIgX/cFGJ96Sxk44QnraJlbBbvA35tb5KCT2JiqF/oWxHFAa1utqqgApEvq/9+1tfyk7G7Q30ZBGHWiVkhDYwQesseAa6rgZnPaYc0zHmyY9GjEdDy7WL85; Path=/; Secure; HttpOnly, Connection: Close, Date: Fri, 10 Sep 2021 16:19:51 GMT, Expires: Thu, 01 Dec 1994 16:00:00 GMT, Cache-Control: no-cache="set-cookie, set-cookie2"] ResponseEntityProxy{[Content-Type: application/json; charset=UTF-8,Content-Length: 74,Chunked: false]}}
**java.lang.Exception: class java.util.Optional cannot be cast to class java.lang.String (java.util.Optional and java.lang.String are in module java.base of loader 'bootstrap')
	at utility.UtilDataset.checkHttpErrors(UtilDataset.java:65)
	at zosfiles.ZosDsn.createDsn(ZosDsn.java:148)
	at ZosDsnListTest.setUp(ZosDsnListTest.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)**

**Comment by frankgiordano** [comment]
I found the cause of this issue. Due to double Optional assignment. I will fix it.
