### ISSUE TITLE
submitJob throws java.lang.ClassCastException

### ISSUE THREAD

**Issue by corinned** [zowe/zowe-client-java-sdk#244]
Running the following command:

    Job job = submitJobs.submitJob(new Member(partitionedDataset, "BR14").toString());

on a system that is not performing well returns 

java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')

	at zowe.client.sdk.parsejson.ParseJobJson.parse(ParseJobJson.java:49)
	at zowe.client.sdk.parsejson.ParseJobJson.parse(ParseJobJson.java:24)
	at zowe.client.sdk.zosjobs.SubmitJobs.submitJobCommon(SubmitJobs.java:130)
	at zowe.client.sdk.zosjobs.SubmitJobs.submitJob(SubmitJobs.java:77)

The response contains: 
    {"phase":130,"subsystem":"JES2","phase-name":"Job is actively converting"}

**Comment by frankgiordano** [comment]
I made the following change that should resolve the error message:
https://github.com/zowe/zowe-client-java-sdk/commit/ca0bcd5bcf32aa71b5c406d1efaabcf23fcb8ca4

can you pull and build a local Jar and test it?

Make your pom have version 1.0.19, run mvn clean package, and then run these two commands from your other project directory to consume the new local sdk jar file and then you can run with it and test it:
mvn install:install-file -Dfile=C:\Users\fg892105\IdeaProjects\zowe-client-java-sdk\target\zowe-client-java-sdk-1.0.19.jar -DgroupId=org.zowe.client.java.sdk -DartifactId=zowe-client-java-sdk -Dversion=1.0.19 -Dpackaging=jar -DlocalRepositoryPath=C:\Users\fg892105\IdeaProjects\zowe-client-java-sdk-examples\my-repo

mvn install:install-file -Dfile=C:\Users\fg892105\IdeaProjects\zowe-client-java-sdk\target\zowe-client-java-sdk-1.0.19.jar -DgroupId=org.zowe.client.java.sdk -DartifactId=zowe-client-java-sdk -Dversion=1.0.19 -DpomFile=C:\Users\fg892105\IdeaProjects\zowe-client-java-sdk-tests\pom.xml

**Comment by frankgiordano** [comment]
@corinned I will close the issue. It should be resolved now. We can reopen if needed.
